### ISSUE TITLE
DELETE SyntaxError: Unexpected end of input

### ISSUE THREAD

**Issue by dottodot** [kubrickology/mailchimp-v3-api#5]
I'm seem to have an issue on DELETE method as getting the following error.

```
SyntaxError: Unexpected end of input
    at Object.parse (native)
    at IncomingMessage.<anonymous> (/node_modules/mailchimp-v3-api/mailchimp-v3-api.js:115:24)
    at emitNone (events.js:73:20)
    at IncomingMessage.emit (events.js:167:7)
    at endReadableNT (_stream_readable.js:906:12)
    at nextTickCallbackWith2Args (node.js:455:9)
    at process._tickDomainCallback (node.js:410:17)
```

the item is getting deleted though.

**Comment by bobvanluijt** [comment]
Not good, I'll look at it

**Comment by bobvanluijt** [comment]
Fixed https://github.com/kubrickology/mailchimp-v3-api/commit/f604fe7ee6b053b9e5adcbd3d78b6ca2743c9694
